// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using NOAH.Utilities;

namespace NOAH.FundManagement;
public class WorkflowreportmakerTest : BaseConfig
{
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [Test]
    public void workflowreportmaker()
    {
        driver.Value.Navigate().GoToUrl("https://flinoahuat.federalland.ph/FLI_app/login?a=sdasdas2121dsf68j821dgdfyhikjhkj&bb=sdasdas2121dsf68j821dgdfyhikjhk&c=sdasdas2121dsf68j821dgdfyhikjhk&jauas=jaskdashdj23lkklj454545&nwdev=p8dev&jkskdjsfhdhfgdjf=deskskdsdsd&d=sdasdas2121dsf68j821dgdfyhikjhk&a2z4i7e=");
        driver.Value.Manage().Window.Size = new System.Drawing.Size(1936, 1066);
        driver.Value.FindElement(By.Id("txtUsername")).Click();
        driver.Value.FindElement(By.Id("txtUsername")).SendKeys("dpppasamonte");
        driver.Value.FindElement(By.Id("txtPassword")).SendKeys("noah123");
        driver.Value.FindElement(By.Id("txtPassword")).SendKeys(Keys.Enter);
        driver.Value.FindElement(By.CssSelector("#main_menuModule > .toolBar-menu-label")).Click();
        driver.Value.FindElement(By.CssSelector(".txt-search-submenu-module")).Click();
        driver.Value.FindElement(By.CssSelector(".txt-search-submenu-module")).SendKeys("wfm");
        driver.Value.FindElement(By.CssSelector(".txt-search-submenu-module")).SendKeys(Keys.Enter);
        driver.Value.FindElement(By.CssSelector("#noahwebApp-WFM > .toolBar-menu-sub-label")).Click();
        driver.Value.FindElement(By.CssSelector("body > form:nth-child(3) > div:nth-child(4) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(5) > div:nth-child(1) > div:nth-child(1)")).Click();
        {
            var element = driver.Value.FindElement(By.CssSelector("#nw-list5"));
            Actions builder = new Actions(driver.Value);
            builder.DoubleClick(element).Perform();
        }
        {
            var element = driver.Value.FindElement(By.CssSelector("#nw-lista10"));
            Actions builder = new Actions(driver.Value);
            builder.DoubleClick(element).Perform();
        }
        {
            var element = driver.Value.FindElement(By.CssSelector("div[id=\'nws-lista10\'] div[class=\'emi-formtitle\']"));
            Actions builder = new Actions(driver.Value);
            builder.DoubleClick(element).Perform();
        }
        {
            var element = driver.Value.FindElement(By.CssSelector("#emi-WFMWorkFlowperDeptReport"));
            Actions builder = new Actions(driver.Value);
            builder.DoubleClick(element).Perform();
        }
        driver.Value.SwitchTo().Frame("emi-Form-WFMWorkFlowperDeptReport_xform");
        driver.Value.FindElement(By.CssSelector(".noah-webui-containerRow > .noah-webui-containerRow:nth-child(1)")).Click();
        driver.Value.FindElement(By.CssSelector(".noah-webui-containerRowItem > label")).Click();
        driver.Value.FindElement(By.Id("txtDateFrom")).Click();
        driver.Value.FindElement(By.LinkText("20")).Click();
        driver.Value.FindElement(By.CssSelector("#noah-webui-default-Refresh > .noah-webui-Toolbox-Item-Title")).Click();
        Thread.Sleep(3000);
        driver.Value.FindElement(By.CssSelector(".nwCuz-007 > label")).Click();
        driver.Value.FindElement(By.Id("ui-id-5")).Click();
        driver.Value.FindElement(By.Id("atl_UserName")).Click();
        {
            var element = driver.Value.FindElement(By.Id("atl_UserName"));
            Actions builder = new Actions(driver.Value);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.Value.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver.Value);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.Value.FindElement(By.Id("lookupColumn")).Click();
        driver.Value.FindElement(By.CssSelector(".searchDiv > div:nth-child(2)")).Click();
        driver.Value.FindElement(By.Id("txtlookupsearch")).Click();
        driver.Value.FindElement(By.Id("txtlookupsearch")).SendKeys("dpppasamonte");
        driver.Value.FindElement(By.CssSelector(".LookUpRefresh")).Click();
        Thread.Sleep(1000);
        driver.Value.FindElement(By.CssSelector("tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2)")).Click();
        driver.Value.FindElement(By.Id("LookUpAddtoList")).Click();
        driver.Value.FindElement(By.CssSelector("#noah-webui-default-Refresh > .noah-webui-Toolbox-Item-Title")).Click();
        Thread.Sleep(3000);
        driver.Value.FindElement(By.CssSelector(".noah-webui-containerRowItem > label")).Click();
        driver.Value.FindElement(By.Id("txtDateFrom")).Click();
        driver.Value.FindElement(By.LinkText("19")).Click();
        driver.Value.FindElement(By.CssSelector("#noah-webui-default-Refresh > .noah-webui-Toolbox-Item-Title")).Click();
        Thread.Sleep(3000);
    }
}
